---
title: "11_DataCleaning"
output: html_document
---

# Data Cleaning for Project

This RMarkdown document is to clean the raw data, addressing missing observations, filtering variables of interest, and ensuring correct data types. The cleaned data will be saved as `11_dataclean.csv` for use in the analysis steps.

```{r}
library(stargazer)
library(car)
require(graphics)
library(readr)
library(tidyverse)

#Each csv file basically had the same format, all in wide form, 266 countries as columns, and from the years of 1960 to 2024.

#skipping: we skipped the first 4 rows, because they did not provide any actual data.
# column removal: we removed columns 2 to 4 from every csv file because they were country code, data indicators, and variables that did not bring meaningful contributions to the project's goal. 
#All changes apply to all the data sets.

ND <- read.csv("New_DDAY.csv", skip = 4)
hot <- ND[-2:-4]

API <- read.csv("API_A.csv", skip = 4)
hot_2 <- API[-2:-4]

PG <- read.csv("Pop_Growth.csv", skip = 4)
hot_7 <- PG[-2:-4]

DR <- read.csv("Death rate.csv", skip = 4)
hot_3 <- DR[-2:-4]

unemployment <- read.csv("Unemployment.csv", skip = 4)
hot_4 <- unemployment[-2:-4]

Education <- read.csv("Education.csv", skip =4)
hot_5 <- Education[-2:-4]

GDP <- read.csv("API_NY.GDP.PCAP.CD_DS2_en_csv_v2_2518.csv", skip =4)
hot_6 <- GDP[-2:-4]


```

```{r}
#To this point, all csv files are in wide form.
#pivot_longer: we basically just swap the columns and rows.

#So now the columns for the case of df_pr, would have each of the 266 countries stack along with their respected years into two columns.This applies to the remaining df created.

#There are bascially Years, Poverty Rate, Inflation, Population Growth, Unemployment, Education, Death Rate, and GDP.

df_pr <- pivot_longer(hot, cols = X1960:X2024, names_to = "Years", names_prefix = "X", values_to = "Poverty Rate")
df_INf <- pivot_longer(hot_2, cols = X1960:X2024, names_to = "Years", names_prefix = "X", values_to = "Inflation")
df_PG <- pivot_longer(hot_7, cols = X1960:X2024, names_to = "Years", names_prefix = "X", values_to = "Population Growth")
df_DR <- pivot_longer(hot_3, cols = X1960:X2024, names_to = "Years", names_prefix = "X", values_to = "Death Rate")
df_Unempo <- pivot_longer(hot_4, cols = X1960:X2024, names_to = "Years", names_prefix = "X", values_to = "Unempolyment")
df_ED <- pivot_longer(hot_5, cols = X1960:X2024, names_to = "Years", names_prefix = "X", values_to = "Edcuation")
df_GDP <- pivot_longer(hot_6, cols = X1960:X2024, names_to = "Years", names_prefix = "X", values_to = "GDP")
```

```{r}
#Since each variable df now has two columns and 17,290 entries.
#All that is left is to combined each column using merge(). Where we had to create a new df variable inorder to keep on merging the rest of the df.

df_lm <- merge(df_pr,df_INf)

df_lm <- merge(df_lm, df_PG)

df_lm <-merge(df_lm, df_DR)

df_lm <- merge(df_lm, df_Unempo)

df_lm <- merge(df_lm, df_ED)

df_lm <- merge(df_lm, df_GDP)
```


```{r}
write.csv(df_lm, file = "Cleaned_data11.csv", row.names = TRUE)
```

